<?php
/**
 * WFOCO_Snippet_Library — die 5 kuratierten Performance-Fixes als embedded
 * PHP-Strings. Quelle-of-Truth ist src/lib/smartfix-snippets.ts auf
 * website-fix.com; diese PHP-Variante ist 1:1 portiert mit identischen
 * Safety-Checks und Body-Code.
 *
 * Jeder Snippet liefert:
 *   - slug:          stabiler URL-/Datei-Slug
 *   - title:         Anzeige-Name im Admin
 *   - tagline:       1-Satz-Was-tut-es
 *   - problem_tag:   Pill-Label (z.B. "Hoher TTFB · CPU-Last")
 *   - effect:        Erwarteter Effekt in 1-2 Sätzen
 *   - hoster_scope:  "Alle Hoster" / "Mit Cloudflare empfohlen" etc.
 *   - effect_scope:  "Frontend" / "Backend" / "Beides"
 *   - warning:       (optional) Kompat-Hinweis
 *   - code:          das vollständige PHP-Snippet, READY für mu-plugin-Datei
 *                    (inkl. <?php Header, ABSPATH-Check, Safety-Check, Body)
 *
 * Snippets werden mit dem `WebsiteFix One-Click Optimizer`-Marker im File-
 * Header geschrieben — das Uninstall-Script erkennt sie daran und löscht
 * NUR unsere Dateien (keine fremden mu-plugins).
 */

defined( 'ABSPATH' ) || exit;

class WFOCO_Snippet_Library {

    /**
     * Liefert das vollständige Snippet-Array.
     *
     * @return array<int, array<string, mixed>>
     */
    public static function get_all() {
        return array(
            self::snippet_heartbeat(),
            self::snippet_xmlrpc(),
            self::snippet_emojis(),
            self::snippet_query_strings(),
            self::snippet_jquery_migrate(),
            self::snippet_author_archive_block(),
            self::snippet_hide_wp_version(),
        );
    }

    /**
     * Lookup per slug — null wenn nicht vorhanden.
     */
    public static function get( $slug ) {
        foreach ( self::get_all() as $s ) {
            if ( $s['slug'] === $slug ) {
                return $s;
            }
        }
        return null;
    }

    /**
     * Wrappt den Snippet-Body in den standardisierten mu-plugin-Header
     * mit Marker, Datum und Versionierung. Wird beim Apply in die
     * mu-plugin-Datei geschrieben.
     */
    public static function build_file_content( $snippet ) {
        $now    = gmdate( 'Y-m-d H:i:s' );
        $marker = 'WebsiteFix One-Click Optimizer';
        $header = "<?php\n"
            . "/**\n"
            . " * Plugin Name: WebsiteFix Optimizer · " . $snippet['title'] . "\n"
            . " * Description: " . $snippet['tagline'] . "\n"
            . " * Version:     " . WFOCO_VERSION . "\n"
            . " *\n"
            . " * Auto-generated by {$marker} on {$now} UTC.\n"
            . " * Slug: " . $snippet['slug'] . "\n"
            . " *\n"
            . " * Diese Datei wird automatisch entfernt, wenn der entsprechende\n"
            . " * Fix im WebsiteFix-Optimizer-Settings deaktiviert oder das\n"
            . " * Plugin deinstalliert wird. NICHT manuell bearbeiten — Änderungen\n"
            . " * werden beim nächsten Re-Apply überschrieben.\n"
            . " */\n\n"
            . "defined( 'ABSPATH' ) || exit;\n\n";

        return $header . $snippet['code'];
    }

    // ════════════════════════════════════════════════════════════════════════
    // SNIPPET-DEFINITIONEN
    // ════════════════════════════════════════════════════════════════════════

    private static function snippet_heartbeat() {
        return array(
            'slug'         => 'heartbeat-throttle',
            'title'        => 'Heartbeat-API drosseln',
            'tagline'      => 'Reduziert die WordPress-Heartbeat-Frequenz pro Bereich: 60 s im Admin, 120 s im Post-Editor (statt 15 s), Frontend praktisch aus.',
            'problem_tag'  => 'Hoher TTFB · CPU-Last',
            'effect'       => 'Senkt admin-ajax.php-Last um typisch 75–85 %. Spürbar weniger CPU-Verbrauch auf Shared-Hosting, niedrigerer TTFB-Wert.',
            'hoster_scope' => 'Alle Hoster',
            'effect_scope' => 'Backend & Frontend',
            'warning'      => 'Live-WooCommerce-Cart-Fragmente oder BuddyPress-Live-Notifications brauchen Frontend-Heartbeat — in dem Fall ist nur die Drosselung sinnvoll, nicht das wp_deregister_script.',
            'code'         => <<<'PHP'
// ── Auto-Safety-Check: Kollisionen mit anderen Heartbeat-Plugins erkennen ──
$wfoco_active = (array) get_option( 'active_plugins' );
if ( in_array( 'heartbeat-control/heartbeat-control.php', $wfoco_active, true )
  || in_array( 'wp-rocket/wp-rocket.php',                  $wfoco_active, true ) ) {
    if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
        error_log( 'WebsiteFix Optimizer [heartbeat]: skipped — collision detected.' );
    }
    return;
}

add_filter( 'heartbeat_settings', function( $settings ) {
    if ( is_admin() ) {
        $screen = function_exists( 'get_current_screen' ) ? get_current_screen() : null;
        if ( $screen && in_array( $screen->base, array( 'post', 'page' ), true ) ) {
            $settings['interval'] = 120;
        } else {
            $settings['interval'] = 60;
        }
    } else {
        $settings['interval'] = 300;
    }
    return $settings;
}, 10, 1 );

add_action( 'init', function() {
    // Heartbeat auf öffentlichen Seiten komplett deaktivieren.
    if ( ! is_admin() ) {
        wp_deregister_script( 'heartbeat' );
    }
}, 1 );
PHP,
        );
    }

    private static function snippet_xmlrpc() {
        return array(
            'slug'         => 'xmlrpc-disable',
            'title'        => 'XML-RPC & Pingbacks deaktivieren',
            'tagline'      => 'Schließt den XML-RPC-Endpoint (Brute-Force-Angriffsfläche) und schaltet Pingbacks ab. Erkennt aktives Jetpack/Wordfence/Sucuri und greift dann NICHT ein.',
            'problem_tag'  => 'Brute-Force-Schutz · Anti-Spam',
            'effect'       => 'Schließt die häufigste Brute-Force-Angriffsfläche (xmlrpc.php). Reduziert spam-Pingback-Comments. Schützt zusätzlich vor User-Enumeration über /wp-json/wp/v2/users.',
            'hoster_scope' => 'Alle Hoster',
            'effect_scope' => 'Backend',
            'warning'      => 'WordPress-Mobile-App, IFTTT, Hootsuite und ähnliche Tools nutzen XML-RPC zum Posten. Wenn du sowas verwendest: vor Apply in Staging testen.',
            'code'         => <<<'PHP'
// ── Auto-Safety-Check: konfligierende Security-Plugins erkennen ──
$wfoco_active = (array) get_option( 'active_plugins' );
foreach ( array(
    'jetpack/jetpack.php',
    'wordfence/wordfence.php',
    'sucuri-scanner/sucuri.php',
) as $wfoco_skip ) {
    if ( in_array( $wfoco_skip, $wfoco_active, true ) ) {
        if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
            error_log( 'WebsiteFix Optimizer [xmlrpc]: skipped — security plugin manages this (' . $wfoco_skip . ').' );
        }
        return;
    }
}

// XML-RPC vollständig deaktivieren
add_filter( 'xmlrpc_enabled', '__return_false' );

// Pingback-Methoden zusätzlich entfernen (Defense-in-Depth)
add_filter( 'xmlrpc_methods', function( $methods ) {
    unset( $methods['pingback.ping'] );
    unset( $methods['pingback.extensions.getPingbacks'] );
    return $methods;
}, 10, 1 );

// Ausgehende Pingbacks abschalten
add_filter( 'pre_option_default_pingback_flag', '__return_zero' );

// X-Pingback-Header entfernen
add_filter( 'wp_headers', function( $headers ) {
    unset( $headers['X-Pingback'] );
    return $headers;
}, 10, 1 );

// REST-API User-Enumeration für anonyme Anfragen blockieren
add_filter( 'rest_authentication_errors', function( $result ) {
    if ( ! is_user_logged_in() && ! empty( $_SERVER['REQUEST_URI'] )
         && false !== strpos( wp_unslash( $_SERVER['REQUEST_URI'] ), '/wp-json/wp/v2/users' ) ) {
        return new WP_Error( 'rest_not_logged_in', 'Anmeldung erforderlich.', array( 'status' => 401 ) );
    }
    return $result;
}, 10, 1 );
PHP,
        );
    }

    private static function snippet_emojis() {
        return array(
            'slug'         => 'emojis-embeds-bloat-remove',
            'title'        => 'Emojis & oEmbed-Discovery entfernen',
            'tagline'      => 'Entfernt die WordPress-Emoji-Polyfill-Scripte (wp-emoji-release.min.js, ~14 KB) und die oEmbed-Auto-Discovery-Routen.',
            'problem_tag'  => 'Frontend-Bloat · Render-Blocking',
            'effect'       => 'Spart 2-3 HTTP-Requests pro Page-Load + ~14 KB Frontend-Payload. URL-Embeds im Editor bleiben funktional, nur die öffentliche Discovery wird abgeschaltet.',
            'hoster_scope' => 'Alle Hoster',
            'effect_scope' => 'Frontend',
            'warning'      => '',
            'code'         => <<<'PHP'
// ── Auto-Safety-Check: Disable-Emojis-Plugin / Perfmatters managen das schon ──
$wfoco_active = (array) get_option( 'active_plugins' );
if ( in_array( 'disable-emojis/disable-emojis.php', $wfoco_active, true )
  || in_array( 'perfmatters/perfmatters.php',        $wfoco_active, true ) ) {
    if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
        error_log( 'WebsiteFix Optimizer [emojis]: skipped — handled by existing plugin.' );
    }
    return;
}

// ── 1. Emoji-Scripte + Styles aus dem Frontend entfernen ──
remove_action( 'wp_head',             'print_emoji_detection_script', 7 );
remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
remove_action( 'wp_print_styles',     'print_emoji_styles' );
remove_action( 'admin_print_styles',  'print_emoji_styles' );
remove_filter( 'the_content_feed',    'wp_staticize_emoji' );
remove_filter( 'comment_text_rss',    'wp_staticize_emoji' );
remove_filter( 'wp_mail',             'wp_staticize_emoji_for_email' );

// DNS-Prefetch für s.w.org (Emoji-CDN) ebenfalls deaktivieren
add_filter( 'wp_resource_hints', function( $urls, $relation_type ) {
    if ( 'dns-prefetch' === $relation_type ) {
        return array_diff( wp_list_pluck( $urls, 'href' ), array( 'https://s.w.org' ) );
    }
    return $urls;
}, 10, 2 );

// ── 2. oEmbed-Auto-Discovery-Routen entfernen ──
remove_action( 'rest_api_init',         'wp_oembed_register_route' );
remove_filter( 'oembed_dataparse',      'wp_filter_oembed_result', 10 );
remove_action( 'wp_head',               'wp_oembed_add_discovery_links' );
remove_action( 'wp_head',               'wp_oembed_add_host_js' );
PHP,
        );
    }

    private static function snippet_query_strings() {
        return array(
            'slug'         => 'query-string-cleaner',
            'title'        => 'Query-Strings aus statischen Assets entfernen',
            'tagline'      => 'Strippt `?ver=…` aus CSS/JS-Pfaden — Proxy- und CDN-Caches können die Assets sauber cachen.',
            'problem_tag'  => 'CDN-Cache-Hit-Rate · Wasted Bandwidth',
            'effect'       => 'Erhöht die Cache-Hit-Rate von Cloudflare/Hoster-Cache deutlich, weil Assets unter stabiler URL ausgeliefert werden. Spart wiederholten Bandwidth-Verbrauch.',
            'hoster_scope' => 'Alle Hoster (besonders sinnvoll mit Cloudflare oder Hoster-Cache)',
            'effect_scope' => 'Frontend',
            'warning'      => 'Ohne Cache-Plugin und bei häufigen Plugin-/Theme-Updates kann ein einzelner Hard-Refresh nötig sein, bis ein CSS-Update beim User ankommt.',
            'code'         => <<<'PHP'
// ── Auto-Safety-Check: Caching-Plugins erledigen Query-String-Stripping bereits ──
$wfoco_active = (array) get_option( 'active_plugins' );
foreach ( array(
    'wp-rocket/wp-rocket.php',
    'w3-total-cache/w3-total-cache.php',
    'wp-super-cache/wp-cache.php',
) as $wfoco_cache ) {
    if ( in_array( $wfoco_cache, $wfoco_active, true ) ) {
        if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
            error_log( 'WebsiteFix Optimizer [query-strings]: skipped — handled by ' . $wfoco_cache . '.' );
        }
        return;
    }
}

function wfoco_strip_ver_from_assets( $src ) {
    if ( strpos( $src, '?ver=' ) !== false ) {
        $src = remove_query_arg( 'ver', $src );
    }
    return $src;
}
add_filter( 'style_loader_src',  'wfoco_strip_ver_from_assets', 10, 1 );
add_filter( 'script_loader_src', 'wfoco_strip_ver_from_assets', 10, 1 );
PHP,
        );
    }

    private static function snippet_author_archive_block() {
        return array(
            'slug'         => 'author-archive-block',
            'title'        => 'Author-Archive blockieren (User-Enumeration-Schutz)',
            'tagline'      => 'Verhindert Username-Discovery via /?author=N oder /author/<name>/. Bekanntester Brute-Force-Vorbereitungs-Trick wird ausgehebelt.',
            'problem_tag'  => 'User-Enumeration · Brute-Force-Vorstufe',
            'effect'       => 'Aufrufe von /?author=1, /?author=2, ... liefern 301 zur Startseite. Username-Probing zwecks Brute-Force-Vorbereitung wird ineffektiv. Standard-Härtung, die fast keine Site wirklich braucht.',
            'hoster_scope' => 'Alle Hoster',
            'effect_scope' => 'Frontend',
            'warning'      => 'Wenn du Author-Archives bewusst nutzt (z.B. Multi-Autoren-Blog mit /author/jane/-Seiten als Content-Hub): NICHT aktivieren, sonst werden die regulär gewünschten Author-URLs blockiert.',
            'code'         => <<<'PHP'
// ── Auto-Safety-Check: Yoast/All-in-One-SEO haben eigene Author-Archive-Optionen ──
// Wenn dort Author-Archives explizit deaktiviert wurden, brauchen wir nicht doppelt.
$wfoco_active = (array) get_option( 'active_plugins' );
if ( in_array( 'wordpress-seo/wp-seo.php', $wfoco_active, true ) ) {
    $yoast_titles = get_option( 'wpseo_titles' );
    if ( is_array( $yoast_titles ) && ! empty( $yoast_titles['disable-author'] ) ) {
        if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
            error_log( 'WebsiteFix Optimizer [author-block]: skipped — Yoast disable-author already on.' );
        }
        return;
    }
}

// ── Author-Query auf Frontend abfangen ──
add_action( 'template_redirect', function() {
    if ( is_admin() ) return;

    // /?author=N — Standard-Probe-URL
    if ( isset( $_GET['author'] ) ) {
        wp_safe_redirect( home_url( '/' ), 301 );
        exit;
    }

    // /author/<name>/ — wenn Permalinks aktiv
    if ( is_author() ) {
        wp_safe_redirect( home_url( '/' ), 301 );
        exit;
    }
}, 1 );

// ── REST-API: /wp-json/wp/v2/users/<n> auch dichtmachen für anonyme Calls ──
// (XML-RPC-Snippet macht das schon für /users — hier zusätzlich für Einzel-User-Endpoints.)
add_filter( 'rest_authentication_errors', function( $result ) {
    if ( ! is_user_logged_in() && ! empty( $_SERVER['REQUEST_URI'] )
         && preg_match( '#/wp-json/wp/v2/users/\d+#', wp_unslash( $_SERVER['REQUEST_URI'] ) ) ) {
        return new WP_Error( 'rest_not_logged_in', 'Anmeldung erforderlich.', array( 'status' => 401 ) );
    }
    return $result;
}, 10, 1 );
PHP,
        );
    }

    private static function snippet_hide_wp_version() {
        return array(
            'slug'         => 'hide-wp-version',
            'title'        => 'WordPress-Version aus Frontend entfernen',
            'tagline'      => 'Entfernt den Generator-Tag im HTML-Head, im RSS-Feed und in Resource-URL-Versionierungen — Scanner sehen die WordPress-Version nicht mehr direkt.',
            'problem_tag'  => 'Information Disclosure · Security Hygiene',
            'effect'       => 'Externe Scanner und Brute-Force-Bots erkennen die exakte WordPress-Version nicht mehr via /, RSS-Feed oder Asset-?ver=. Macht versions-spezifische Exploit-Sweep-Attacken aufwändiger.',
            'hoster_scope' => 'Alle Hoster',
            'effect_scope' => 'Frontend',
            'warning'      => '',
            'code'         => <<<'PHP'
// ── Auto-Safety-Check: Security-Plugins managen das oft schon ──
$wfoco_active = (array) get_option( 'active_plugins' );
foreach ( array(
    'wordfence/wordfence.php',
    'sucuri-scanner/sucuri.php',
    'all-in-one-wp-security-and-firewall/wp-security.php',
    'perfmatters/perfmatters.php',
) as $wfoco_skip ) {
    if ( in_array( $wfoco_skip, $wfoco_active, true ) ) {
        if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
            error_log( 'WebsiteFix Optimizer [hide-wp-version]: skipped — handled by ' . $wfoco_skip . '.' );
        }
        return;
    }
}

// 1. Generator-Tag im <head> entfernen
remove_action( 'wp_head', 'wp_generator' );

// 2. Filter den Generator-Output zusätzlich leer-string — manche Themes geben ihn selbst aus
add_filter( 'the_generator', '__return_empty_string' );

// 3. RSS-Feed-Generator (XML-Header) ebenfalls dichtmachen
foreach ( array( 'rss2_head', 'commentsrss2_head', 'rss_head', 'rdf_header', 'atom_head', 'comments_atom_head', 'opml_head', 'app_head' ) as $wfoco_feed ) {
    add_action( $wfoco_feed, function() {
        // No-op — überschreibt nichts, aber der Generator-Hook läuft hier nicht mehr durch
    }, 0 );
}

// 4. WordPress-Version aus Asset-URLs entfernen — falls Query-String-Cleaner-Fix
//    NICHT aktiv ist, würde ?ver=6.4.3 die Version verraten. Dieser Block neutralisiert
//    GENAU diese WP-Versions-Spur (ohne andere ?ver=-Strings zu touchen).
add_filter( 'style_loader_src', function( $src ) {
    return remove_query_arg( array( 'ver', 'v' ), $src );
}, 9999 );
add_filter( 'script_loader_src', function( $src ) {
    return remove_query_arg( array( 'ver', 'v' ), $src );
}, 9999 );
PHP,
        );
    }

    private static function snippet_jquery_migrate() {
        return array(
            'slug'         => 'jquery-migrate-remove',
            'title'        => 'jQuery-Migrate aus dem Frontend entfernen',
            'tagline'      => 'Entfernt jquery-migrate.min.js (~11 KB) aus dem Frontend, lässt sie im Admin aber aktiv.',
            'problem_tag'  => 'Frontend-Bloat · Legacy-Code',
            'effect'       => 'Spart ~11 KB Frontend-Payload + einen HTTP-Request. Lighthouse-Performance-Score steigt typisch um 1-3 Punkte.',
            'hoster_scope' => 'Alle Hoster',
            'effect_scope' => 'Frontend',
            'warning'      => 'Bei Themes älter als 2020 oder Custom-Code mit Konstrukten wie $.browser oder $.live() vor dem Aktivieren in Staging testen — diese Patterns würden ohne Migrate brechen.',
            'code'         => <<<'PHP'
// ── Auto-Safety-Check: Disable-jQuery-Migrate / Perfmatters managen das ──
$wfoco_active = (array) get_option( 'active_plugins' );
foreach ( array(
    'disable-jquery-migrate/disable-jquery-migrate.php',
    'perfmatters/perfmatters.php',
) as $wfoco_skip ) {
    if ( in_array( $wfoco_skip, $wfoco_active, true ) ) {
        if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
            error_log( 'WebsiteFix Optimizer [jquery-migrate]: skipped — handled by ' . $wfoco_skip . '.' );
        }
        return;
    }
}

add_action( 'wp_default_scripts', function( $scripts ) {
    if ( is_admin() ) {
        return;
    }
    if ( ! empty( $scripts->registered['jquery'] ) ) {
        $deps = $scripts->registered['jquery']->deps;
        $scripts->registered['jquery']->deps = array_diff(
            (array) $deps,
            array( 'jquery-migrate' )
        );
    }
}, 1, 1 );

// Optional: jQuery-Migrate-Console-Warnings unterdrücken
add_filter( 'script_loader_tag', function( $tag, $handle ) {
    if ( 'jquery-migrate' === $handle && ! is_admin() ) {
        return '';
    }
    return $tag;
}, 10, 2 );
PHP,
        );
    }
}
